### ISSUE TITLE
Tornado Example Error

### ISSUE THREAD

**Issue by brentalanmiller** [eleme/thriftpy#123]
I'm trying to run the simplest thiftypy 0.2.0 / tornado 4.1 example I can find. So, I came across the docstring example in thiftpy/tornado.py

I set up a pingpong server, and although I can get an rpc client working fine, a tornado client as shown in the docstring will always fail with a TTransportException. So the following script:

```python
import logging

import thriftpy.rpc
import thriftpy.tornado

from tornado import ioloop

pingpong_thrift = thriftpy.load("pingpong.thrift", module_name="pingpong_thrift")

def rpc_test():
    client = thriftpy.rpc.make_client(pingpong_thrift.PingPong, '127.0.0.1', 6000)
    
    return client.ping()

def tornado_test():
    client = ioloop.IOLoop.current().run_sync(
        lambda: thriftpy.tornado.make_client(pingpong_thrift.PingPong, '127.0.0.1', 6000))
    
    return ioloop.IOLoop.current().run_sync(client.ping)

if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    
    print rpc_test()
    print tornado_test()
```

will yield:
```
pong
DEBUG:root:socket connecting
Traceback (most recent call last):
  File "/home/bamiller/workspace/DmHbase/thriftpy_test_client.py", line 25, in <module>
    print tornado_test()
  File "/home/bamiller/workspace/DmHbase/thriftpy_test_client.py", line 19, in tornado_test
    return ioloop.IOLoop.current().run_sync(client.ping)
  File "/home/bamiller/opt/python/local/lib/python2.7/site-packages/tornado/ioloop.py", line 421, in run_sync
    return future_cell[0].result()
  File "/home/bamiller/opt/python/local/lib/python2.7/site-packages/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "/home/bamiller/opt/python/local/lib/python2.7/site-packages/tornado/gen.py", line 810, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/home/bamiller/opt/python/local/lib/python2.7/site-packages/thriftpy/tornado.py", line 195, in _recv
    frame = yield self._oprot.trans.read_frame()
  File "/home/bamiller/opt/python/local/lib/python2.7/site-packages/tornado/gen.py", line 807, in run
    value = future.result()
  File "/home/bamiller/opt/python/local/lib/python2.7/site-packages/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "/home/bamiller/opt/python/local/lib/python2.7/site-packages/tornado/gen.py", line 810, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/home/bamiller/opt/python/local/lib/python2.7/site-packages/thriftpy/tornado.py", line 124, in read_frame
    raise gen.Return(frame)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/bamiller/opt/python/local/lib/python2.7/site-packages/thriftpy/tornado.py", line 100, in io_exception_context
    message=str(e))
thriftpy.transport.TTransportException: TTransportException(message='', type=4)
```

I can run the test case in tests/test_tornado.py so I'm guessing there's nothing wrong with the version of thriftypy / tornado I'm using, but if there was a little bit more in the way of examples / docs that would be really helpful.

Thanks!

**Comment by eyeofthefrog** [comment]
I had a similar error, and then I remembered something when working with Apache Thrift. The tornado code will use a framed transport. If you switch your server to use a framed transport, this may work. I'm doing the opposite (tornado server and RPC client) and switching the client to use a framed transport is what got this to work for me.
