### ISSUE TITLE
参数中带有中文的时候报错

### ISSUE THREAD

**Issue by hellorocky** [eleme/thriftpy#228]
```py
Traceback (most recent call last):
  File "client.py", line 15, in <module>
    client.sendwx("wufeiqun", u"Hi,728,吴飞群!".encode("utf-8"))
  File "/home/rocky/pyenv/lib/python2.7/site-packages/thriftpy/thrift.py", line 160, in _req
    return self._recv(_api)
  File "/home/rocky/pyenv/lib/python2.7/site-packages/thriftpy/thrift.py", line 172, in _recv
    fname, mtype, rseqid = self._iprot.read_message_begin()
  File "thriftpy/protocol/cybin/cybin.pyx", line 429, in cybin.TCyBinaryProtocol.read_message_begin (thriftpy/protocol/cybin/cybin.c:6312)
  File "thriftpy/protocol/cybin/cybin.pyx", line 60, in cybin.read_i32 (thriftpy/protocol/cybin/cybin.c:1531)
  File "thriftpy/transport/buffered/cybuffered.pyx", line 65, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.c_read (thriftpy/transport/buffered/cybuffered.c:1872)
  File "thriftpy/transport/buffered/cybuffered.pyx", line 69, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.read_trans (thriftpy/transport/buffered/cybuffered.c:1939)
  File "thriftpy/transport/cybase.pyx", line 61, in thriftpy.transport.cybase.TCyBuffer.read_trans (thriftpy/transport/cybase.c:1463)
  File "/home/rocky/pyenv/lib/python2.7/site-packages/thriftpy/transport/socket.py", line 125, in read
    message='TSocket read 0 bytes')
thriftpy.transport.TTransportException: TTransportException(message='TSocket read 0 bytes', type=4)
```

**Comment by lxyu** [comment]
The current implementation should work for Chinese chars. Can you provide a full reproduce script?

**Comment by wufeiqun** [comment]
client side 

```
#!/usr/bin/env python
#coding: utf-8
import os
import json
import datetime
import thriftpy
from thriftpy.rpc import make_client

now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

if __name__ == "__main__":
    file_path = os.path.abspath("simple.thrift")
    simple_thrift = thriftpy.load(file_path, module_name = "simple_thrift")
    client = make_client(simple_thrift.SENDWX, "172.100.102.101", 6000)
    client.sendwx("wufeiqun", u"三十岁".encode("utf-8"))
```

simple.thrift

```
service SENDWX {
    string sendwx(1:string touser,2:string content),
}
```

server side

```
#!/usr/bin/env python
#coding: utf-8

......省略一些变量定义代码

class MyRPC(object):
    def sendwx(self, touser, content):
        headers = {'Content-Type': 'application/json', "charset": "utf-8"}
        msg     = { 'touser': touser, 'msgtype': 'text', 'agentid': WXQY_AGENT_ID, 'text': {'content': content}}
        msg     = json.dumps(msg, ensure_ascii=False, encoding="utf-8")
        access_token = get_access_token()
        ret = requests.post(WXQY_API_SENDWX, params={'access_token': access_token}, data=msg, headers=headers, verify=False).json()
        return "OK"

if __name__ == "__main__":
    file_path = os.path.abspath("simple.thrift")
    simple_thrift = thriftpy.load(file_path, module_name = "simple_thrift")
    server = make_server(simple_thrift.SENDWX, MyRPC(), "172.100.102.101", 6000)
    server.serve()


```

@lxyu

**Comment by hellorocky** [comment]
原谅我的英文不是很好,我用中文表达吧,我发现一个bug,我看到thrift官网定义`string`类型传输的时候都是`utf-8`的,但是我使用thriftpy模块的时候,不管客户端是否encode成utf-8,服务端接收到的数据类型永远都是`unicode`的.

**Comment by lxyu** [comment]
无法重现，并且:
1. traceback 的错误和中文无关
2. 检查下非中文的参数是否正确
3. 看看你是否有权限 bind 到 172.100.102.101 的端口上。

**Comment by February00** [comment]
你好，请问你的问题解决了么？是怎么解决的，我的报错内容是一样的，但是我的参数中不包含中文
