### ISSUE TITLE
TApplicationException: Missing result

### ISSUE THREAD

**Issue by JennyHui** [eleme/thriftpy#235]
using thriftpy in my test code, in server the log has return the result but raise this 'TApplicationException: Missing result'

**Comment by lxyu** [comment]
@JennyHui may you please provide a detailed reproduce script or steps?

**Comment by JennyHui** [comment]
@lxyu here ~

fake code:
1. set up the test data

``` py
YODA_THRIFT = thriftpy.load(dirname+"/resource/thrift/yoda.thrift", module_name="yoda_thrift")
client = make_client(config.YODA_THRIFT.YodaService, config.THRIFT_HOST, config.THRIFT_PORT)
direct_strategy = YODA_THRIFT.DirectStrategy() //the struct
```
1.  testing

``` py
result = client.create_direct_strategy(direct_strategy)
```

i've run a lot of time of this, and some of time it works but most of the time the "result" just turn out to be error:

``` py
query_grids_contain_point_result(system_exception=None, user_exception=None, success=None, unknown_exception=None) // print this result 
Error
Traceback (most recent call last):
  File "/Users/jennyhui/PycharmProjects/ClairSoaClient/lib/python2.7/site-packages/thriftpy/thrift.py", line 160, in _req
    return self._recv(_api)
  File "/Users/jennyhui/PycharmProjects/ClairSoaClient/lib/python2.7/site-packages/thriftpy/thrift.py", line 197, in _recv
    raise TApplicationException(TApplicationException.MISSING_RESULT)
TApplicationException: Missing result
```

**Comment by lxyu** [comment]
You're calling `create_direct_strategy` api and the traceback shows `query_grids_contain_point_result` api. It do not match.

Can you try to minimize the reproduce script and post one here?

**Comment by tonyzhu** [comment]
I get the same error.

**Comment by guangbaowan** [comment]
I get the same error.

**Comment by CanoeFZH** [comment]
I get the same error.

**Comment by ghost** [comment]
I get the same error.

**Comment by AlexKeepLearning** [comment]
I get the same error

**Comment by wooparadog** [comment]
Everybody here. Please provide detailed reproduction steps, including server and client code. We have also encountered this error, but all of those are network/server implantation related problems, well outside the scope of thriftpy.

And the client implementation in thriftpy is not ready for heavy production, please use github.com/eleme/thrift_connector instead.

**Comment by vEpiphyte** [comment]
> And the client implementation in thriftpy is not ready for heavy production

@wooparadog Is there still a concern about the stability of the client implementation in thriftpy?

cc: @jnwatson

**Comment by wooparadog** [comment]
There's no problem with client implementation in thriftpy itself, just that
it's too bare for production use. It's ok if your work load is not so
great, but if it is, take a look at thrift connector(connection pool etc..)
