### ISSUE TITLE
struct can't contain more than 254 fields

### ISSUE THREAD

**Issue by terwilliger42** [eleme/thriftpy#244]
When you add more than 254 fields to a struct, the attributes do not get initialized, the object cannot be serialized, etc.

Traceback (most recent call last):
  File "thrift_test.py", line 7, in <module>
    x = many.field1
AttributeError: 'ManyFields' object has no attribute 'field1'

Test case:
[many_fields.zip](https://github.com/eleme/thriftpy/files/517107/many_fields.zip)

**Comment by terwilliger42** [comment]
The issue here is that python functions cannot take more than 255 arguments, and the generated **init** function sets a default argument for each field.  This results in compile(..) raising a SyntaxError exception which (to make matters even worse) gets gobbled up by ply.

Will submit a pull request with a fix.

**Comment by hit9** [comment]
What's your python version? I cannot reproduce your code in your attachment.

**Comment by terwilliger42** [comment]
I can reproduce this using Python 3.4.4 and 3.5.1, but not 2.7.11:
```
$ venv27/bin/python --version
Python 2.7.11
$ venv27/bin/python thrift_test.py 
$ venv34/bin/python --version
Python 3.4.4
$ venv34/bin/python thrift_test.py
Traceback (most recent call last):
  File "thrift_test.py", line 5, in <module>
    x = many.field1
AttributeError: 'ManyFields' object has no attribute 'field1'
$ venv35/bin/python --version
Python 3.5.1
$ venv35/bin/python thrift_test.py
Traceback (most recent call last):
  File "thrift_test.py", line 5, in <module>
    x = many.field1
AttributeError: 'ManyFields' object has no attribute 'field1'
```

**Comment by lxyu** [comment]
FYI

http://stackoverflow.com/questions/714475/what-is-a-maximum-number-of-arguments-in-a-python-function
