### ISSUE TITLE
Local .thrift file don't get picked up on Windows.

### ISSUE THREAD

**Issue by ErKatz** [eleme/thriftpy#269]
On windows when the path start with the "file://" scheme, I get the following error: 
(path is 'file://C:\\Users\\MrT\\UserSegmentation\\lib\\site-packages\\happybase\\Hbase.thrift')

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Erez.Katz\UserSegmentation\Lib\site-packages\happybase\__init__.py", line 10, in <module>
    'Hbase_thrift')
  File "C:\Users\Erez.Katz\UserSegmentation\Lib\site-packages\thriftpy\parser\__init__.py", line 30, in load
    include_dir=include_dir)
  File "C:\Users\Erez.Katz\UserSegmentation\Lib\site-packages\thriftpy\parser\parser.py", line 496, in parse
    url_scheme))
thriftpy.parser.exc.ThriftParserError: ThriftPy does not support generating module with path in protocol 'file'

workaround that I added in my environment in thriftpy\parser\parser.py", around starting at line 540

    url_scheme = urlparse(path).scheme
    if url_scheme == 'file':
        with open(urlparse(path).netloc) as fh:
            data = fh.read()
    elif url_scheme == '':
        with open(path) as fh:
            data = fh.read()
    elif url_scheme in ('http', 'https'):
        data = urlopen(path).read()
    else:
        raise ThriftParserError('ThriftPy does not support generating module '
                                'with path in protocol \'{}\''.format(
                                    url_scheme))

**Comment by ErKatz** [comment]
this also impacts
https://github.com/wbolster/happybase/issues/148
