### ISSUE TITLE
It support set<i32> or map<string, string> or list<i16>?

### ISSUE THREAD

**Issue by linzhi** [eleme/thriftpy#290]
//struct Set {
//   1: required set<string> a_set
//}

service SpiderService {
    string send_url();
    i32 receive_url(1: set<string> urls);
}

But it cause  thriftpy.parser.exc.ThriftGrammerError: Grammer error 'set' at line 3

**Comment by linzhi** [comment]
[ERROR] [2017-04-12 15:00:55] [spider:123] * 发送urls给master异常, 异常信息: Traceback (most recent call last):
  File "spider.py", line 121, in send_url
    res = self.master_spider.receive_url(urls)
  File "/usr/local/lib/python2.7/site-packages/thriftpy/thrift.py", line 198, in _req
    return self._recv(_api)
  File "/usr/local/lib/python2.7/site-packages/thriftpy/thrift.py", line 210, in _recv
    fname, mtype, rseqid = self._iprot.read_message_begin()
  File "thriftpy/protocol/cybin/cybin.pyx", line 429, in cybin.TCyBinaryProtocol.read_message_begin (thriftpy/protocol/cybin/cybin.c:6325)
  File "thriftpy/protocol/cybin/cybin.pyx", line 60, in cybin.read_i32 (thriftpy/protocol/cybin/cybin.c:1546)
  File "thriftpy/transport/buffered/cybuffered.pyx", line 65, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.c_read (thriftpy/transport/buffered/cybuffered.c:1881)
  File "thriftpy/transport/buffered/cybuffered.pyx", line 69, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.read_trans (thriftpy/transport/buffered/cybuffered.c:1948)
  File "thriftpy/transport/cybase.pyx", line 61, in thriftpy.transport.cybase.TCyBuffer.read_trans (thriftpy/transport/cybase.c:1472)
  File "/usr/local/lib/python2.7/site-packages/thriftpy/transport/socket.py", line 125, in read
    message='TSocket read 0 bytes')
TTransportException: TTransportException(message='TSocket read 0 bytes', type=4)
