### ISSUE TITLE
Hava a question.. it offen display Broken pipe

### ISSUE THREAD

**Issue by linzhi** [eleme/thriftpy#292]
Traceback (most recent call last):
  File "spider.py", line 49, in get_url
    url = self.master_spider.send_url()
  File "/usr/local/lib/python2.7/site-packages/thriftpy/thrift.py", line 195, in _req
    self._send(_api, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/thriftpy/thrift.py", line 201, in _send
    self._oprot.write_message_begin(_api, TMessageType.CALL, self._seqid)
  File "thriftpy/protocol/cybin/cybin.pyx", line 454, in cybin.TCyBinaryProtocol.write_message_begin (thriftpy/protocol/cybin/cybin.c:6721)
  File "thriftpy/protocol/cybin/cybin.pyx", line 83, in cybin.write_i32 (thriftpy/protocol/cybin/cybin.c:1777)
  File "thriftpy/transport/buffered/cybuffered.pyx", line 55, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.c_write (thriftpy/transport/buffered/cybuffered.c:1753)
  File "thriftpy/transport/buffered/cybuffered.pyx", line 80, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.c_flush (thriftpy/transport/buffered/cybuffered.c:2147)
  File "/usr/local/lib/python2.7/site-packages/thriftpy/transport/socket.py", line 129, in write
    self.sock.sendall(buff)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 32] Broken pipe

**Comment by wjiang720** [comment]
Hey linzhi, 

Did you figure out the solution to this issue? I am having the same issue now.

Thanks,
Wendy
